-- Run once in a Snowsight worksheet. Trial accounts are time- and credit-limited,
-- so the resource monitor below is not optional.
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS FACTOR_MART_RM
  WITH CREDIT_QUOTA = 20
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS FACTOR_MART_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = FACTOR_MART_RM;

CREATE DATABASE IF NOT EXISTS FACTOR_MART;
CREATE SCHEMA IF NOT EXISTS FACTOR_MART.CORE;
